### ISSUE TITLE
sitemaps returning invalid changefreq value

### ISSUE THREAD

**Issue by othbert** [softspring/cms-bundle#205]
please see:
https://ch.librio.com/sitemap.xml

contains changefreq values of "0" for many routes, I guess this should be picking the default changefreq setup for the site, but 0 is marked as invalid by google search console, should be a string with a value representing 'hourly', 'daily', 'weekly', 'monthly' ... etc

https://www.sitemaps.org/protocol.html

**Comment by javihgil** [comment]
You're right, there is a bug. XmlEncoder converts float to rounded number on string casting.
